; 安装程序初始定义常量
!define PRODUCT_NAME "NUAA Snatcher"
!define PRODUCT_VERSION "1.2b"
!define PRODUCT_PUBLISHER "dboycht"
!define PRODUCT_WEB_SITE "https://github.com/dboycht/NUAA-Snatcher"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\ui_manager.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

SetCompressor lzma

; ------ MUI 现代界面定义 (1.67 版本以上兼容) ------
!include "MUI.nsh"

; MUI 预定义常量
!define MUI_ABORTWARNING
!define MUI_ICON "C:\Users\micak\Desktop\1.2b\icon.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; 欢迎页面
!insertmacro MUI_PAGE_WELCOME
; 许可协议页面
!define MUI_LICENSEPAGE_RADIOBUTTONS
!insertmacro MUI_PAGE_LICENSE "C:\Users\micak\Desktop\1.2b\license.txt"
; 安装目录选择页面
!insertmacro MUI_PAGE_DIRECTORY
; 开始菜单设置页面
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "NUAA Snatcher"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; 安装过程页面
!insertmacro MUI_PAGE_INSTFILES
; 安装完成页面
!define MUI_FINISHPAGE_RUN "$INSTDIR\ui_manager.exe"
!insertmacro MUI_PAGE_FINISH

; 安装卸载过程页面
!insertmacro MUI_UNPAGE_INSTFILES

; 安装界面包含的语言设置
!insertmacro MUI_LANGUAGE "SimpChinese"

; 安装预释放文件
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
; ------ MUI 现代界面定义结束 ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\NUAA Snatcher"
InstallDirRegKey HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
ShowInstDetails show
ShowUnInstDetails show
BrandingText " "

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "C:\Users\micak\Desktop\1.2b\ui_manager.exe"
  File "C:\Users\micak\Desktop\1.2b\icon.ico"
  File "C:\Users\micak\Desktop\1.2b\license.txt"
  File "C:\Users\micak\Desktop\1.2b\snatcher.ui"
  SetOutPath "$INSTDIR\_internal"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-console-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-datetime-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-debug-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-errorhandling-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-fibers-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-file-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-file-l1-2-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-file-l2-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-handle-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-heap-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-interlocked-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-libraryloader-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-localization-l1-2-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-memory-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-namedpipe-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-processenvironment-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-processthreads-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-processthreads-l1-1-1.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-profile-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-rtlsupport-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-string-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-synch-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-synch-l1-2-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-sysinfo-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-timezone-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-core-util-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-conio-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-convert-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-environment-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-filesystem-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-heap-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-locale-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-math-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-process-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-runtime-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-stdio-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-string-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-time-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\api-ms-win-crt-utility-l1-1-0.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\base_library.zip"
  SetOutPath "$INSTDIR\_internal\certifi"
  File "C:\Users\micak\Desktop\1.2b\_internal\certifi\cacert.pem"
  File "C:\Users\micak\Desktop\1.2b\_internal\certifi\py.typed"
  SetOutPath "$INSTDIR\_internal\charset_normalizer"
  File "C:\Users\micak\Desktop\1.2b\_internal\charset_normalizer\md.cp312-win_amd64.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\charset_normalizer\md__mypyc.cp312-win_amd64.pyd"
  SetOutPath "$INSTDIR\_internal\cryptography\hazmat\bindings"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography\hazmat\bindings\_rust.pyd"
  SetOutPath "$INSTDIR\_internal\cryptography-46.0.3.dist-info"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\INSTALLER"
  SetOutPath "$INSTDIR\_internal\cryptography-46.0.3.dist-info\licenses"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE.APACHE"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE.BSD"
  SetOutPath "$INSTDIR\_internal\cryptography-46.0.3.dist-info"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\METADATA"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\RECORD"
  File "C:\Users\micak\Desktop\1.2b\_internal\cryptography-46.0.3.dist-info\WHEEL"
  SetOutPath "$INSTDIR\_internal"
  File "C:\Users\micak\Desktop\1.2b\_internal\icon.ico"
  File "C:\Users\micak\Desktop\1.2b\_internal\libcrypto-3.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\libffi-8.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\libssl-3.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\pyexpat.pyd"
  SetOutPath "$INSTDIR\_internal\PySide6"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\MSVCP140.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\MSVCP140_1.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\MSVCP140_2.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\opengl32sw.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\generic"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\generic\qtuiotouchplugin.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\iconengines"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\imageformats"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qgif.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qicns.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qico.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qjpeg.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qpdf.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qsvg.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qtga.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qtiff.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qwbmp.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\networkinformation"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\networkinformation\qnetworklistmanager.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\platforminputcontexts"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\platforminputcontexts\qtvirtualkeyboardplugin.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\platforms"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\platforms\qdirect2d.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\platforms\qminimal.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\platforms\qoffscreen.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\platforms\qwindows.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\styles"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\styles\qmodernwindowsstyle.dll"
  SetOutPath "$INSTDIR\_internal\PySide6\plugins\tls"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\tls\qcertonlybackend.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\tls\qopensslbackend.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\plugins\tls\qschannelbackend.dll"
  SetOutPath "$INSTDIR\_internal\PySide6"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\pyside6.abi3.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Core.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Gui.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Network.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6OpenGL.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6OpenGLWidgets.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Pdf.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Qml.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6QmlMeta.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6QmlModels.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6QmlWorkerScript.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Quick.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Svg.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6UiTools.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6VirtualKeyboard.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\Qt6Widgets.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtCore.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtGui.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtNetwork.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtOpenGL.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtOpenGLWidgets.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtUiTools.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\QtWidgets.pyd"
  SetOutPath "$INSTDIR\_internal\PySide6\translations"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ar.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_bg.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ca.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_cs.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_da.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_de.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_en.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_es.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_fa.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_fi.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_fr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_gd.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_he.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_hr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_hu.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_it.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ja.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ka.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ko.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_lg.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_lv.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_nl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_nn.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_pl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_pt_BR.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_ru.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_sk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_sv.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_tr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_uk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_zh_CN.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qtbase_zh_TW.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ar.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_bg.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ca.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_cs.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_da.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_de.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_en.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_es.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_fa.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_fi.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_fr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_gd.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_gl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_he.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ar.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_bg.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ca.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_cs.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_da.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_de.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_en.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_es.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_fr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_gl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_hr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_hu.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_it.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ja.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ka.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ko.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_nl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_nn.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_pl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_pt_BR.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_ru.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_sk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_sl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_sv.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_tr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_uk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_zh_CN.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_help_zh_TW.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_hr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_hu.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_it.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ja.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ka.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ko.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_lg.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_lt.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_lv.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_nl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_nn.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_pl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_pt_BR.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_pt_PT.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_ru.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_sk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_sl.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_sv.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_tr.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_uk.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_zh_CN.qm"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\translations\qt_zh_TW.qm"
  SetOutPath "$INSTDIR\_internal\PySide6"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\VCRUNTIME140.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\PySide6\VCRUNTIME140_1.dll"
  SetOutPath "$INSTDIR\_internal"
  File "C:\Users\micak\Desktop\1.2b\_internal\python3.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\python312.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\select.pyd"
  SetOutPath "$INSTDIR\_internal\shiboken6"
  File "C:\Users\micak\Desktop\1.2b\_internal\shiboken6\MSVCP140.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\shiboken6\Shiboken.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\shiboken6\shiboken6.abi3.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\shiboken6\VCRUNTIME140.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\shiboken6\VCRUNTIME140_1.dll"
  SetOutPath "$INSTDIR\_internal"
  File "C:\Users\micak\Desktop\1.2b\_internal\snatcher.ui"
  File "C:\Users\micak\Desktop\1.2b\_internal\ucrtbase.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\unicodedata.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\VCRUNTIME140.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\VCRUNTIME140_1.dll"
  File "C:\Users\micak\Desktop\1.2b\_internal\_asyncio.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_bz2.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_cffi_backend.cp312-win_amd64.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_ctypes.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_decimal.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_hashlib.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_lzma.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_multiprocessing.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_overlapped.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_queue.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_socket.pyd"
  File "C:\Users\micak\Desktop\1.2b\_internal\_ssl.pyd"

; 创建开始菜单快捷方式
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\NUAA Snatcher.lnk" "$INSTDIR\ui_manager.exe"
  CreateShortCut "$DESKTOP\NUAA Snatcher.lnk" "$INSTDIR\ui_manager.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\ui_manager.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\ui_manager.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

/******************************
 *  以下是安装程序的卸载部分  *
 ******************************/

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\_internal\_ssl.pyd"
  Delete "$INSTDIR\_internal\_socket.pyd"
  Delete "$INSTDIR\_internal\_queue.pyd"
  Delete "$INSTDIR\_internal\_overlapped.pyd"
  Delete "$INSTDIR\_internal\_multiprocessing.pyd"
  Delete "$INSTDIR\_internal\_lzma.pyd"
  Delete "$INSTDIR\_internal\_hashlib.pyd"
  Delete "$INSTDIR\_internal\_decimal.pyd"
  Delete "$INSTDIR\_internal\_ctypes.pyd"
  Delete "$INSTDIR\_internal\_cffi_backend.cp312-win_amd64.pyd"
  Delete "$INSTDIR\_internal\_bz2.pyd"
  Delete "$INSTDIR\_internal\_asyncio.pyd"
  Delete "$INSTDIR\_internal\VCRUNTIME140_1.dll"
  Delete "$INSTDIR\_internal\VCRUNTIME140.dll"
  Delete "$INSTDIR\_internal\unicodedata.pyd"
  Delete "$INSTDIR\_internal\ucrtbase.dll"
  Delete "$INSTDIR\_internal\snatcher.ui"
  Delete "$INSTDIR\_internal\shiboken6\VCRUNTIME140_1.dll"
  Delete "$INSTDIR\_internal\shiboken6\VCRUNTIME140.dll"
  Delete "$INSTDIR\_internal\shiboken6\shiboken6.abi3.dll"
  Delete "$INSTDIR\_internal\shiboken6\Shiboken.pyd"
  Delete "$INSTDIR\_internal\shiboken6\MSVCP140.dll"
  Delete "$INSTDIR\_internal\select.pyd"
  Delete "$INSTDIR\_internal\python312.dll"
  Delete "$INSTDIR\_internal\python3.dll"
  Delete "$INSTDIR\_internal\PySide6\VCRUNTIME140_1.dll"
  Delete "$INSTDIR\_internal\PySide6\VCRUNTIME140.dll"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_zh_TW.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_zh_CN.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_uk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_tr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_sv.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_sl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_sk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ru.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_pt_PT.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_pt_BR.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_pl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_nn.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_nl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_lv.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_lt.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_lg.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ko.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ka.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ja.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_it.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_hu.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_hr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_zh_TW.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_zh_CN.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_uk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_tr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_sv.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_sl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_sk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ru.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_pt_BR.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_pl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_nn.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_nl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ko.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ka.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ja.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_it.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_hu.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_hr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_gl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_fr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_es.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_en.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_de.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_da.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_cs.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ca.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_bg.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_help_ar.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_he.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_gl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_gd.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_fr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_fi.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_fa.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_es.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_en.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_de.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_da.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_cs.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ca.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_bg.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qt_ar.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_zh_TW.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_zh_CN.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_uk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_tr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_sv.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_sk.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ru.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_pt_BR.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_pl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_nn.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_nl.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_lv.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_lg.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ko.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ka.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ja.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_it.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_hu.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_hr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_he.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_gd.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_fr.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_fi.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_fa.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_es.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_en.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_de.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_da.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_cs.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ca.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_bg.qm"
  Delete "$INSTDIR\_internal\PySide6\translations\qtbase_ar.qm"
  Delete "$INSTDIR\_internal\PySide6\QtWidgets.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtUiTools.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtOpenGLWidgets.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtOpenGL.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtNetwork.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtGui.pyd"
  Delete "$INSTDIR\_internal\PySide6\QtCore.pyd"
  Delete "$INSTDIR\_internal\PySide6\Qt6Widgets.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6VirtualKeyboard.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6UiTools.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Svg.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Quick.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6QmlWorkerScript.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6QmlModels.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6QmlMeta.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Qml.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Pdf.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6OpenGLWidgets.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6OpenGL.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Network.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Gui.dll"
  Delete "$INSTDIR\_internal\PySide6\Qt6Core.dll"
  Delete "$INSTDIR\_internal\PySide6\pyside6.abi3.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\tls\qschannelbackend.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\tls\qopensslbackend.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\tls\qcertonlybackend.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\styles\qmodernwindowsstyle.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\platforms\qwindows.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\platforms\qoffscreen.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\platforms\qminimal.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\platforms\qdirect2d.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\platforminputcontexts\qtvirtualkeyboardplugin.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\networkinformation\qnetworklistmanager.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qwebp.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qwbmp.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qtiff.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qtga.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qsvg.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qpdf.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qjpeg.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qico.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qicns.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\imageformats\qgif.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\_internal\PySide6\plugins\generic\qtuiotouchplugin.dll"
  Delete "$INSTDIR\_internal\PySide6\opengl32sw.dll"
  Delete "$INSTDIR\_internal\PySide6\MSVCP140_2.dll"
  Delete "$INSTDIR\_internal\PySide6\MSVCP140_1.dll"
  Delete "$INSTDIR\_internal\PySide6\MSVCP140.dll"
  Delete "$INSTDIR\_internal\pyexpat.pyd"
  Delete "$INSTDIR\_internal\libssl-3.dll"
  Delete "$INSTDIR\_internal\libffi-8.dll"
  Delete "$INSTDIR\_internal\libcrypto-3.dll"
  Delete "$INSTDIR\_internal\icon.ico"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\WHEEL"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\RECORD"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\METADATA"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE.BSD"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE.APACHE"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\licenses\LICENSE"
  Delete "$INSTDIR\_internal\cryptography-46.0.3.dist-info\INSTALLER"
  Delete "$INSTDIR\_internal\cryptography\hazmat\bindings\_rust.pyd"
  Delete "$INSTDIR\_internal\charset_normalizer\md__mypyc.cp312-win_amd64.pyd"
  Delete "$INSTDIR\_internal\charset_normalizer\md.cp312-win_amd64.pyd"
  Delete "$INSTDIR\_internal\certifi\py.typed"
  Delete "$INSTDIR\_internal\certifi\cacert.pem"
  Delete "$INSTDIR\_internal\base_library.zip"
  Delete "$INSTDIR\_internal\api-ms-win-crt-utility-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-time-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-string-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-stdio-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-runtime-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-process-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-math-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-locale-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-heap-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-filesystem-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-environment-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-convert-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-crt-conio-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-util-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-timezone-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-sysinfo-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-synch-l1-2-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-synch-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-string-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-rtlsupport-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-profile-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-processthreads-l1-1-1.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-processthreads-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-processenvironment-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-namedpipe-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-memory-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-localization-l1-2-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-libraryloader-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-interlocked-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-heap-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-handle-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-file-l2-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-file-l1-2-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-file-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-fibers-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-errorhandling-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-debug-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-datetime-l1-1-0.dll"
  Delete "$INSTDIR\_internal\api-ms-win-core-console-l1-1-0.dll"
  Delete "$INSTDIR\snatcher.ui"
  Delete "$INSTDIR\license.txt"
  Delete "$INSTDIR\icon.ico"
  Delete "$INSTDIR\ui_manager.exe"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$DESKTOP\NUAA Snatcher.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\NUAA Snatcher.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\_internal\shiboken6"
  RMDir "$INSTDIR\_internal\PySide6\translations"
  RMDir "$INSTDIR\_internal\PySide6\plugins\tls"
  RMDir "$INSTDIR\_internal\PySide6\plugins\styles"
  RMDir "$INSTDIR\_internal\PySide6\plugins\platforms"
  RMDir "$INSTDIR\_internal\PySide6\plugins\platforminputcontexts"
  RMDir "$INSTDIR\_internal\PySide6\plugins\networkinformation"
  RMDir "$INSTDIR\_internal\PySide6\plugins\imageformats"
  RMDir "$INSTDIR\_internal\PySide6\plugins\iconengines"
  RMDir "$INSTDIR\_internal\PySide6\plugins\generic"
  RMDir "$INSTDIR\_internal\PySide6"
  RMDir "$INSTDIR\_internal\cryptography-46.0.3.dist-info\licenses"
  RMDir "$INSTDIR\_internal\cryptography-46.0.3.dist-info"
  RMDir "$INSTDIR\_internal\cryptography\hazmat\bindings"
  RMDir "$INSTDIR\_internal\charset_normalizer"
  RMDir "$INSTDIR\_internal\certifi"
  RMDir "$INSTDIR\_internal"

  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd

#-- 根据 NSIS 脚本编辑规则，所有 Function 区段必须放置在 Section 区段之后编写，以避免安装程序出现未可预知的问题。--#

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "您确实要完全移除 $(^Name) ，及其所有的组件？" IDYES +2
  Abort
FunctionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从您的计算机移除。"
FunctionEnd
